### ISSUE TITLE
MarketNames

### ISSUE THREAD

**Issue by Gismor** [menimani/TOSAddon#1]
Hello i have try your marketnames addon but it dosent work.

In the addon Folder i have a folder "marketnames_ex" in this folder is my list with the names the data have the name
"marketnames-1003.txt"
but it dosent work.
what is wrong?

**Comment by menimani** [comment]
@Gismor 
Sorry for my late reply
Please change the name of the folder "marketnames_ex" to "marketnames"
Since we had to unify name management in all versions, the "marketnames" folder is used

**Comment by Gismor** [comment]
okay i have donwload the new version and have rename the folder. 
now in my "marketnames" folder is my data 
"marketnames-1003.txt" is this the right name for the data but i see nothing names :(

**Comment by menimani** [comment]
> okay i have donwload the new version and have rename the folder.
> now in my "marketnames" folder is my data

okay you can run this add-on.

> "marketnames-1003.txt" is this the right name for the data but i see nothing names :(

I think it is caused by the absence of a name in "marketnames-1003.txt".
Player names not registered in "marketnames-1003.txt" can not be displayed.
To add a name to "marketnames-1003.txt", you need to go near other players.
If you can get "marketnames-1003.txt" from players on the same server, you can display many player names.

**Comment by menimani** [comment]
If it still does not work, it takes time to investigate.

**Comment by Gismor** [comment]
nope nothing :( 
the .txt file is full with 
PlayerID Charname Teamname
but do not appear in the market.

**Comment by menimani** [comment]
Please execute attached file
Is it displayed as an attached image?
When it is not displayed like an image
Please submit a screen shot of the market screen and system message

[marketnames.zip](https://github.com/menimani/TOSAddon/files/2550073/marketnames.zip)
![image](https://user-images.githubusercontent.com/20136578/48018747-fb195f00-e174-11e8-851b-a8bfd847b0e3.png)

**Comment by Gismor** [comment]
![screenshot_20181105_00001](https://user-images.githubusercontent.com/14973405/48019719-60009500-e134-11e8-8ee4-93de4db1e198.jpg)

and this name looks on every item in the market.

**Comment by Gismor** [comment]
maybe is the problem jTOS use the older Cient Version than iTOS?
with the new big update there are many changes in the marketsystem

**Comment by menimani** [comment]
yes, jTOS R10 update 10/24/2018
I did not know the large update

If you know the patch in the patch folder, please send it.
If iTOS patch can not be obtained
It seems necessary to wait for jTOS to be updated

**Comment by menimani** [comment]
@Gismor 
I'm sorry to have kept you waiting.
I tried to update marketnames but it was useless

On add-ons, only the range that the user can obtain is allowed to change
However, with this update, it became impossible to acquire others' exhibition information.

If it is made available here, it will exceed the category of add-on, so we can not develop any more.

It seems marketnames were not convenient for IMC. :(

**Comment by Gismor** [comment]
yes i have heard about it but thanks for checking it now marketnames are dead.
lets wait for rebirth :D
